var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                          o                                     ",
   "                          @                                                     ",
   "                       ggggggg         ggggggg                                  ",
   "                       xxxxxxx         xxxxxxx                                  ",
   "                       xxxxxxx         xxxxxxx                                  ",
   "                       xxxxxxx         xxxxxxx                                  ",
   "                       xxxxxxx         xxxxxxx                                  ",
   "                       xxxxxxx         xxxxxxx                                  ",
   "                       xxxxxxx         xxxxxxx                                  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                ",
   "                                                ",
   "                                                ",
   "                                                ",
   "                                                ",
   "                                                ",
   "                                                ",
   "                                                ",
   "                                                ",
   "                                                ",
   "     o                                          ",
   "                                                ",
   "ggggggggggg         gggggggggggggggg      xxxxxx",
   "xxxxxxxxxxx         xxxxxxxxxxxxxxxx      xxxxxx",
   "xxxxxxxxx           xxxxxxxxxxxxxxxx      xxxxxx",
   "xxxxxxxx            xxxxxxxxxxxxxxxx      xxxxxx",
   "xxxx                                     xxxxxxx",
   "xxxx  @                                 xxxxxxxx",
   "xxxx                                   xxxxxxxxx",
   "xxxxggggggg!!!!!!!ggggggggggggggggggggxxxxxxxxxx",
   "xxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"] ,
     ["                                                                                                                                ",
      "                                                                                                                                ",
      "                                                                                                                                ",
      "                                                                                                                                ",
      "                                                                                                                                ",
      "                                                                                                            x              o    ",
      "   @                                                                               xx             x  x                          ",
      "gggggggggggggggg    ggggggggggggggggggggg       gggggggggggggggggggggggggggggggg           xxx                      x  xxxxxxxxx",
      "xxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
      "xxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
      "xxxxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxxx!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
      "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
      ["                              ",
       "       x     x  x  x   x      ",
       "       x  x  x     xx  x      ",
       "       x x x x  x  x x x      ",
       "       xx   xx  x  x  xx      ",
       "                              ",
       "   @                          ",
       "gggggggggggggggggggggggggggggg",
       "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
       "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
       "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
       "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
